### ISSUE TITLE
Data format mismatch

### ISSUE THREAD

**Issue by RafaRuiz** [mobui/gs1_barcode_parser#11]
```
Data format mismatch RegExp: pattern=^01(\d{14})$ flags= for AI 01
```

for value:
`0150602641158911020414891725122811210101`

**Comment by sachebotarev** [comment]
Hi
 GS1 Application Identifier 01 Must be 14 characters long (see https://ref.gs1.org/ai/01). In our example length is 13

![image](https://github.com/user-attachments/assets/54be4b06-19f6-498f-8a54-cd85ce3b8dcc)

**Comment by RafaRuiz** [comment]
It makes sense.
Yet I've got a medical product with 13 characters, which barcode is ean13 and is the same than the one from after `01` to `�`.
Is it possible to parse ignoring the GS1-01?

**Comment by sachebotarev** [comment]
Hi,
 I have added the ability to define custom AI to the library  (version 1.1.0). Custom element have highest priority
Now you can add your own description of an AI element that conflicts with the standard.
Look at the test custom_ai_test.dart, I took your example as a basis

``` dart
     final parser =
        GS1BarcodeParser.configurableParser(GS1BarcodeParserConfig(customAIs: {
      '01': const AI(
        code: '01',
        fixLength: 13,
        type: AIFormatType.FIXED_LENGTH,
        dataTitle: 'GTIN',
        regExpString: r'^01(\d{13})$',
        description: 'EAN13',
      ),
    }));
```
Test it, please

**Comment by RafaRuiz** [comment]
All good, I guess I'll enable an use case with several parsers.
Thanks.
