### ISSUE TITLE
Typo in ai.dart class

### ISSUE THREAD

**Issue by aac-le** [mobui/gs1_barcode_parser#2]
Hey,

yesterday I started using your lib. I really like it, but I think there is a typo in the `ai.dart` class.

Line 165 - 172

`'20': const AI(
      code: '16',
      type: AIFormatType.FIXED_LENGTH,
      dataTitle: 'VARIANT',
      regExpString: r'^20(\d{2})$',
      fixLength: 2,
      description: 'Internal product variant',
    ),`

I think it should be.

`'20': const AI(
      code: '20',
      type: AIFormatType.FIXED_LENGTH,
      dataTitle: 'VARIANT',
      regExpString: r'^20(\d{2})$',
      fixLength: 2,
      description: 'Internal product variant',
    ),`

I would be nice, if you take care of that. 

Best regards

Andreas

**Comment by sachebotarev** [comment]
Hi. 
Thanks.
Fix it. Use version 1.0.1
