### ISSUE TITLE
Unable to decode GS1 String

### ISSUE THREAD

**Issue by yusufola** [mobui/gs1_barcode_parser#3]
Hello, 

I started using your library, it parsed some strings without hassle but was unable to parse this GS1 Portugal string 

0105609380810435212674577536673210A2075I0172509307149507343 (copied from terminal)

Error is` AI not found for 7149507343`

This is the last part of the code but I'm guessing it wasn't able to find an application identifier with 71 or 714 .

There is a GS1 AI for 714 
710-714 | National Healthcare Reimbursement Number (NHRN)

 Sources
 [https://www.tec-it.com/en/support/knowbase/gs1-application-identifier/Default.aspx](url)
 [https://www.gs1.org/standards/barcodes/application-identifiers/714](url)

Can these be include in the list of AI?

Also my expectation is that it will display the AIs it has decoded and identified and ignore the part of the string it hasn't especially since it is the last part of the string.

**Comment by sachebotarev** [comment]
Hello!
I add AI 71* parser, as a temporary solution.
I'll think about how to allow you to add your own AI (processing which is not in the library) or suppress the exception.

**Comment by sachebotarev** [comment]
Try 1.0.2 version

**Comment by yusufola** [comment]
Version 1.0.2 worked. 
Thank you.
